on: [push, pull_request]
name: Build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Variable
        run: echo "::set-output name=DATE_NOW::$(date +'%d/%m/%Y')"
        id: ec2  
      - name: Check the date
        run: |
          echo ${{ steps.ec2.outputs.DATE_NOW }}
      - uses: actions/checkout@v2
        with: 
          path: './' 
      - name: check
        run: |
          echo value=$(cat ./config.json | jq -r '.base_config[1].value')
      - name: Json
        run: echo "::set-output name=JSON_NO::$(cat ./config.json | jq -r '.base_config[1].value')"
        id: json
      - name: Json check
        run: |
          echo num=${{ steps.json.outputs.JSON_NO }}
          echo $(( num+1 ))
        
#         env:
#           NUM: ${{ steps.json.outputs.JSON_NO }}         
#       - run: |
#           echo "::`set-NUM name=JSON_NEW::$(($NUM+1))`"
#           echo $JSON_NEW 
       
      - uses: actions/checkout@v2
        with: 
          path: './'      
      - run: |          
          echo "`jq '.base_config[0].value="Alpha-13"' ./config.json `" > ./config.json 
          echo "`jq '.base_config[1].value="1.2.14"' ./config.json `" > ./config.json 
          echo "`jq '.base_config[2].value="${{ steps.ec2.outputs.DATE_NOW }}"' ./config.json `" > ./config.json 
     
      - uses: EndBug/add-and-commit@v6
        with:
          message: 'Add the version and date'
          add: '*.json --force'
          cwd: './' 
          token: ${{ secrets.TOKEN }} 
        
