on: [push, pull_request]
name: Build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Variable
        run: echo "::set-output name=DATE_NOW::$(date +'%d/%m/%Y')"
        id: ec2  
      - name: Check the date
        run: |
          echo ${{ steps.ec2.outputs.DATE_NOW }}
      - uses: actions/checkout@v2
        with: 
          path: './' 
      - name: check
        env:
          NUM: cat ./config.json | jq -r '.base_config[1].value'
        run:  |
         echo $NUM
         echo ::set-env name=JSON_NO::$(($NUM+0.0.1)) 
      - run: echo $JSON_NO
       
      - uses: actions/checkout@v2
        with: 
          path: './'      
      - run: |          
          echo "`jq '.base_config[0].value="Alpha-13"' ./config.json `" > ./config.json 
          echo "`jq '.base_config[1].value="1.2.14"' ./config.json `" > ./config.json 
          echo "`jq '.base_config[2].value="${{ steps.ec2.outputs.DATE_NOW }}"' ./config.json `" > ./config.json 
     
      - uses: EndBug/add-and-commit@v6
        with:
          message: 'Add the version and date'
          add: '*.json --force'
          cwd: './' 
          token: ${{ secrets.TOKEN }} 
        
