on: [push, pull_request]
env:
  json-access: ${{ secrets.TOKEN_SCOPE }} 
name: Build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Variable
        run: echo "::set-output name=DATE_NOW::$(date +'%d/%m/%Y')"
        id: ec2  
      - name: Check the date
        run: |
          echo ${{ steps.ec2.outputs.DATE_NOW }}
      - uses: actions/checkout@v2
        with: 
          path: './'    
      - name: Secret
        with:
          json-access: ${{ env.json-access }}    
      - name: JSON value
        id: json
        run: |
          echo "::set-output name=JSON_VALUE::$( ./config.json | jq '.base_config[0].value')" 
      - name: Check
        run: |    
          echo "${{ steps.json.outputs.JSON_VALUE }}"
  
      - uses: actions/checkout@v2
        with: 
          path: './'      
      - run: |          
          echo "`jq '.base_config[0].value="Alpha-21"' ./generator/services/configurationmanager/src/assests/configuration.json `" > ./generator/services/configurationmanager/src/assests/configuration.json
          echo "`jq '.base_config[1].value="1.2.14"' ./generator/services/configurationmanager/src/assests/configuration.json `" > ./generator/services/configurationmanager/src/assests/configuration.json
          echo "`jq '.base_config[2].value="${{ steps.ec2.outputs.DATE_NOW }}"' ./generator/services/configurationmanager/src/assests/configuration.json `" > ./generator/services/configurationmanager/src/assests/configuration.json
     
      - uses: EndBug/add-and-commit@v6
        with:
          message: 'Add the version and date'
          add: '*.json --force'
          cwd: './' 
          token: ${{ secrets.TOKEN }} 
        
